version: '3'

services:
  ceron-analyze:
    image: u6kapps/ceron-analyze
    environment:
      - "S3_URL=http://minio:9000/"
      - "S3_BUCKET=ceron"
      - "S3_ACCESS_ID=${DOCKER_MINIO_ACCESS_KEY}"
      - "S3_SECRET_KEY=${DOCKER_MINIO_SECRET_KEY}"
      - "VIRTUAL_HOST=ceron-analyze.u6k.me,ceron-analyze.192.168.3.200.xip.io"
      - "VIRTUAL_PORT=8080"
      - "LETSENCRYPT_HOST=ceron-analyze.u6k.me"
      - "LETSENCRYPT_EMAIL=u6k.apps@gmail.com"
    restart: always

networks:
  default:
    external:
      name: docker_default
