- name: install ufw
  apt: name=ufw
- name: ufw default DENY
  command: ufw default DENY
- name: ufw allow 80
  command: ufw allow 80
- name: ufw allow 443
  command: ufw allow 443
- name: ufw allow ssh
  command: ufw allow {{ ssh_port }}
- name: ufw --force enable
  command: ufw --force enable
- name: ufw status
  command: ufw status
