version: '3'

services:
  blog:
    image: u6kapps/blog
    environment:
      - "VIRTUAL_HOST=blog.u6k.me,blog.192.168.3.200.xip.io"
      - "VIRTUAL_PORT=80"
      - "LETSENCRYPT_HOST=blog.u6k.me"
      - "LETSENCRYPT_EMAIL=u6k.apps@gmail.com"
    restart: always

networks:
  default:
    external:
      name: docker_default
