version: '3'

services:
  app:
    image: u6kapps/blog
    environment:
      - "VIRTUAL_HOST=${DOCKER_BLOG_VIRTUAL_HOST}"
      - "VIRTUAL_PORT=80"
      - "LETSENCRYPT_HOST=${DOCKER_BLOG_LETSENCRYPT_HOST}"
      - "LETSENCRYPT_EMAIL=${DOCKER_BLOG_LETSENCRYPT_EMAIL}"
    restart: always

networks:
  default:
    external:
      name: production
