#cloud-config

hostname: coreos

write_files:
  - path: /etc/environment
    permissions: 0644
    content: |
      DOCKER_VOLUME_PATH=/var/docker-volumes
      REDMINE_MYSQL_PASS=secret
      OWNCLOUD_MYSQL_PASS=secret
      ZABBIX_DB_PASS=secret
  - path: /opt/bin/docker-nginx-proxy.sh
    permissions: 0744
    content: |
      #!/bin/sh
      docker run \
        --name nginx-proxy \
        --privileged \
        -p 80:80 \
        -p 443:443 \
        -v $DOCKER_VOLUME_PATH/nginx-proxy:/etc/nginx/certs:ro \
        -v /etc/nginx/vhost.d \
        -v /usr/share/nginx/html \
        -v /var/run/docker.sock:/tmp/docker.sock:ro \
        u6kapps/nginx-proxy
  - path: /opt/bin/docker-letsencrypt-nginx-proxy-companion.sh
    permissions: 0744
    content: |
      #!/bin/sh
      docker run \
        --name letsencrypt-nginx-proxy-companion \
        --privileged \
        -v $DOCKER_VOLUME_PATH/nginx-proxy:/etc/nginx/certs:rw \
        -v /var/run/docker.sock:/var/run/docker.sock:ro \
        --volumes-from nginx-proxy \
        u6kapps/letsencrypt-nginx-proxy-companion
coreos:
  units:
    - name: etcd.service
      command: start
    - name: docker.service
      command: start
    - name: timezone.service
      command: start
      content: |
        [Unit]
        Description=timezone
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/ln -sf ../usr/share/zoneinfo/Japan /etc/localtime
    - name: mnt-data.mount
      command: start
      content: |
        [Mount]
        What=/dev/disk/by-uuid/5384dc84-1c48-459f-b337-c5839a76162f
        Where=/mnt/data
        Type=ext4
    - name: docker-nginx-proxy.service
      command: start
      content: |
        [Unit]
        Description=nginx-proxy container
        Documentation=https://github.com/u6k/nginx-proxy
        Requires=docker.service
        After=docker.service
        [Service]
        Type=simple
        EnvironmentFile=/etc/environment
        ExecStartPre=-/usr/bin/docker stop nginx-proxy
        ExecStartPre=-/usr/bin/docker rm nginx-proxy
        ExecStartPre=/usr/bin/docker pull u6kapps/nginx-proxy
        ExecStart=/opt/bin/docker-nginx-proxy.sh
        [Install]
        WantedBy=multi-user.target
    - name: docker-letsencrypt-nginx-proxy-companion.service
      command: start
      content: |
        [Unit]
        Description=letsencrypt-nginx-proxy-companion container
        Documentation=https://github.com/u6k/nginx-proxy
        Requires=docker.service docker-nginx-proxy.service
        After=docker.service docker-nginx-proxy.service
        [Service]
        Type=simple
        EnvironmentFile=/etc/environment
        ExecStartPre=-/usr/bin/docker stop letsencrypt-nginx-proxy-companion
        ExecStartPre=-/usr/bin/docker rm letsencrypt-nginx-proxy-companion
        ExecStartPre=/usr/bin/docker pull u6kapps/letsencrypt-nginx-proxy-companion
        ExecStart=/opt/bin/docker-letsencrypt-nginx-proxy-companion.sh
        [Install]
        WantedBy=multi-user.target

users:
  - name: u6k
    passwd: $1$6dXJA246$2HCEnF3W2LcDYvNSREA4n0
    groups:
      - sudo
      - docker
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAEAQD9BCawE47HvgZiPpVeEka50pSVzm9tOUtNVUaJy01OdiJKpHAX+4jt96TVDNSpe0o/2R9tNftFHpn3161OmpEjHukzRo6h6GtqMsa7GmG3vlD3227IXGOwNnsxm7OFvPmjXxPnttUfNoJtMPr4mKiw4nGZCvLPEot/Y9Aogul1vutvdg1Gc42r2l2G9LmrEuUh5fS28CQOlpHL+SwMV39znXHvDugPf0t5lzS1t20fhbVdvciGIUtlWhrFEsM8Bs/rvrrBW8d88efqhGRIMe3cAPS9FiC4l7YF+Yx3U+fBQBFqlIgg9s2VxQ6kMw963AZ7Ep1goafiFdwmVcLQbnGL6IwLj1fu83v58LALDA5O+sB59ZIRJDVG4SKrhCGqoq0rySh8ZW2471joUai60OB+QMYBpqu7u18VgUiQWTDXgRSL4Sd2Ec6L0EZhQx6dzrmruKXuhIK/g9YL5tg2Obs/UHflBO1eOBw5fVgJnMaXcEwHDkLAWVHPsFAwBX9rOlCEdNKKqdRZS9KImObkVEJV1cxcCye7ki3wRqDyZm7hhIOvcCzKE3H3MIRxt5VI3g0Q4xA5CSAFeANdscBHz86tgV5Kcz7qo6ByAxaPz+pvAmw/ldnpoooS8DYBODKhe8TR91GeG1xXl/SBKmm4UisYNn1m6BUX/kPGOhd5ev1QXmmbXcePvh+G5x1qrErBlQ++dUzE68WuGLCquf9bxgIk17V1IYkZm+AkK/A4dddJBFWUN9DYtEFhvjZL6aEBoWcIYvIYCz+x/NGVrbndBJlcShUuWwDHcC2nCO8OAZpUatd6NfPiQHQENHwNFz1jJk/NCE82HtCso7yVwgO4jgs7OrVTRZs2jn38G35zfQtcGJVyHfxpLNWWQV9ywlbTsuh7x4+yQrZYYUx0Ak6nrjNgCJ5R8mGt6w0Dc+0B7ZEOHBQEDu58CDERnwApB2QHwJyJ63S0Ixi/oiY/YsAOh7TODaTRhN04cQkQLHRgWQukTL13Nr5PcG8QKX7QeSbLImgwayuGyn+liBVdlkLNahOvmQPHpTj2gnrZrdlm8976O77wZlB9uYSw8SLbRuAgGBeXEOrLicq0ZLmLYKpoXBKbOx9J7eG7AK9ROYMc4vCVTVGF2+9jh/ErbOposGwPeX344ZNfLVTnCBA+NwCL57G2t/Jjdr5EGXzmapmAZCi9fLjmiHtoEYcf+xL5dbxtT9fVhlurtDk0dsrucmO44g9YUu/9qVZiKNxhVaF272wQQjCeKsbCZ/sIG2920zCZNUKFRM5vCWL7lmqNJTZsRkyKYZDRCu7ZIcozWKY9fkl8B7Ps1VPd/cRG+xD5GdhGNhgWMIS44Z1XiTX6M+T9re3F
