#cloud-config

write_files:
  - path: /etc/environment
    permissions: 0644
    content: |
      DOCKER_VOLUMES=/var/docker-volumes
      DOCKER_REDMINE_DB_USERNAME=redmine_db_user_secret
      DOCKER_REDMINE_DB_PASSWORD=redmine_db_pass_secret
      DOCKER_REDMINE_DB_DATABASE=redmine_db_secret

coreos:
  units:
    - name: docker.service
      command: start
    - name: sshd.socket
      command: restart
      runtime: true
      content: |
        [Socket]
        ListenStream=2222
        FreeBind=true
        Accept=yes
    - name: timezone.service
      command: start
      content: |
        [Unit]
        Description=timezone
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/ln -sf ../usr/share/zoneinfo/Japan /etc/localtime
    - name: install-docker-compose.service
      command: start
      content: |
        [Unit]
        Description=Install docker-compose
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStartPre=-/usr/bin/mkdir -p /opt/bin
        ExecStart=/usr/bin/curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-Linux-x86_64 -o /opt/bin/docker-compose
        ExecStartPost=-/usr/bin/chmod +x /opt/bin/docker-compose
    - name: start-docker-compose.service
      command: start
      content: |
        [Unit]
        Description=Start docker-compose
        Requires=docker.service install-docker-compose.service
        After=docker.service install-docker-compose.service
        [Service]
        Type=simple
        EnvironmentFile=/etc/environment
        ExecStartPre=-/usr/bin/curl -L https://gist.github.com/u6k/bca7cbcc5403f66b40c2600d8253c188/raw/5568c5cc086b6abbd4894ee9568f4439ee1f5a5f/docker-compose.digitalocean.yml -o /home/core/docker-compose.yml
        ExecStart=/opt/bin/docker-compose -f /home/core/docker-compose.yml up -d

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAEAQD9BCawE47HvgZiPpVeEka50pSVzm9tOUtNVUaJy01OdiJKpHAX+4jt96TVDNSpe0o/2R9tNftFHpn3161OmpEjHukzRo6h6GtqMsa7GmG3vlD3227IXGOwNnsxm7OFvPmjXxPnttUfNoJtMPr4mKiw4nGZCvLPEot/Y9Aogul1vutvdg1Gc42r2l2G9LmrEuUh5fS28CQOlpHL+SwMV39znXHvDugPf0t5lzS1t20fhbVdvciGIUtlWhrFEsM8Bs/rvrrBW8d88efqhGRIMe3cAPS9FiC4l7YF+Yx3U+fBQBFqlIgg9s2VxQ6kMw963AZ7Ep1goafiFdwmVcLQbnGL6IwLj1fu83v58LALDA5O+sB59ZIRJDVG4SKrhCGqoq0rySh8ZW2471joUai60OB+QMYBpqu7u18VgUiQWTDXgRSL4Sd2Ec6L0EZhQx6dzrmruKXuhIK/g9YL5tg2Obs/UHflBO1eOBw5fVgJnMaXcEwHDkLAWVHPsFAwBX9rOlCEdNKKqdRZS9KImObkVEJV1cxcCye7ki3wRqDyZm7hhIOvcCzKE3H3MIRxt5VI3g0Q4xA5CSAFeANdscBHz86tgV5Kcz7qo6ByAxaPz+pvAmw/ldnpoooS8DYBODKhe8TR91GeG1xXl/SBKmm4UisYNn1m6BUX/kPGOhd5ev1QXmmbXcePvh+G5x1qrErBlQ++dUzE68WuGLCquf9bxgIk17V1IYkZm+AkK/A4dddJBFWUN9DYtEFhvjZL6aEBoWcIYvIYCz+x/NGVrbndBJlcShUuWwDHcC2nCO8OAZpUatd6NfPiQHQENHwNFz1jJk/NCE82HtCso7yVwgO4jgs7OrVTRZs2jn38G35zfQtcGJVyHfxpLNWWQV9ywlbTsuh7x4+yQrZYYUx0Ak6nrjNgCJ5R8mGt6w0Dc+0B7ZEOHBQEDu58CDERnwApB2QHwJyJ63S0Ixi/oiY/YsAOh7TODaTRhN04cQkQLHRgWQukTL13Nr5PcG8QKX7QeSbLImgwayuGyn+liBVdlkLNahOvmQPHpTj2gnrZrdlm8976O77wZlB9uYSw8SLbRuAgGBeXEOrLicq0ZLmLYKpoXBKbOx9J7eG7AK9ROYMc4vCVTVGF2+9jh/ErbOposGwPeX344ZNfLVTnCBA+NwCL57G2t/Jjdr5EGXzmapmAZCi9fLjmiHtoEYcf+xL5dbxtT9fVhlurtDk0dsrucmO44g9YUu/9qVZiKNxhVaF272wQQjCeKsbCZ/sIG2920zCZNUKFRM5vCWL7lmqNJTZsRkyKYZDRCu7ZIcozWKY9fkl8B7Ps1VPd/cRG+xD5GdhGNhgWMIS44Z1XiTX6M+T9re3F
