version: '3'

services:
  web:
    image: u6kapps/investment-horse-racing-crawler
    environment:
      - "TZ=Asia/Tokyo"
      - "VIRTUAL_HOST=horse-racing-crawler.u6k.me"
      - "VIRTUAL_PORT=5000"
      - "LETSENCRYPT_HOST=horse-racing-crawler.u6k.me"
      - "LETSENCRYPT_EMAIL=u6k.apps@gmail.com"
      - "S3_ENDPOINT=${DOCKER_S3_ENDPOINT}"
      - "S3_REGION=${DOCKER_S3_REGION}"
      - "S3_ACCESS_KEY=${DOCKER_S3_ACCESS_KEY}"
      - "S3_SECRET_KEY=${DOCKER_S3_SECRET_KEY}"
      - "S3_BUCKET=${DOCKER_HORSE_RACING_S3_BUCKET}"
      - "S3_FOLDER=${DOCKER_HORSE_RACING_S3_FOLDER}"
      - "DB_HOST=${DOCKER_HORSE_RACING_DB_HOST}"
      - "DB_PORT=${DOCKER_HORSE_RACING_DB_PORT}"
      - "DB_USERNAME=${DOCKER_HORSE_RACING_DB_USERNAME}"
      - "DB_PASSWORD=${DOCKER_HORSE_RACING_DB_PASSWORD}"
      - "DB_DATABASE=${DOCKER_HORSE_RACING_DB_DATABASE}"
    depends_on:
      - "db"
    restart: always

  db:
    image: postgres:11
    volumes:
      - "${DOCKER_VOLUMES}/horse-racing-crawler/db:/var/lib/postgresql/data"
      - "${DOCKER_VOLUMES}/horse-racing-crawler/wal_archive:/archive"
    environment:
      - "POSTGRES_USER=${DOCKER_HORSE_RACING_DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DOCKER_HORSE_RACING_DB_PASSWORD}"
      - "POSTGRES_DB=${DOCKER_HORSE_RACING_DB_DATABASE}"
    shm_size: 2gb
    restart: always

networks:
  default:
    external:
      name: production
