version: '3'

services:
  app:
    image: u6kapps/extract-content
    environment:
      - "VIRTUAL_HOST=${DOCKER_EXTRACT_CONTENT_VIRTUAL_HOST}"
      - "VIRTUAL_PORT=5000"
      - "LETSENCRYPT_HOST=${DOCKER_EXTRACT_CONTENT_LETSENCRYPT_HOST}"
      - "LETSENCRYPT_EMAIL=${DOCKER_EXTRACT_CONTENT_LETSENCRYPT_EMAIL}"
    restart: always

networks:
  default:
    external:
      name: production
