version: '3'

services:
  app:
    image: minio/minio
    volumes:
      - ${DOCKER_VOLUMES}/minio/export:/export
      - ${DOCKER_VOLUMES}/minio/config:/root/.minio
    command: server /export
    restart: always

networks:
  default:
    external:
      name: production
