version: '3'

services:
  minio:
    image: minio/minio
    volumes:
      - "${DOCKER_VOLUMES}/minio/export:/export"
      - "${DOCKER_VOLUMES}/minio/config:/root/.minio"
    environment:
      - "MINIO_ACCESS_KEY=${DOCKER_MINIO_ACCESS_KEY}"
      - "MINIO_SECRET_KEY=${DOCKER_MINIO_SECRET_KEY}"
      - "VIRTUAL_HOST=minio.u6k.me,minio.192.168.3.200.xip.io"
      - "VIRTUAL_PORT=9000"
      - "LETSENCRYPT_HOST=minio.u6k.me"
      - "LETSENCRYPT_EMAIL=u6k.apps@gmail.com"
    command: server /export
    restart: always

networks:
  default:
    external:
      name: docker_default
