version: '2'

services:
  zabbix-db:
    image: zabbix/zabbix-db-mariadb
    environment:
      - MARIADB_USER=zabbix_user
      - MARIADB_PASS=zabbix_pass
    volumes:
      - /mnt/data/docker/zabbix/mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    restart: always
  zabbix-server:
    image: zabbix/zabbix-3.0:latest
    environment:
      - ZS_DBHost=zabbix.db
      - ZS_DBUser=zabbix_user
      - ZS_DBPassword=zabbix_pass
      - VIRTUAL_HOST=zabbix.u6k.me
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=zabbix.u6k.me
      - LETSENCRYPT_EMAIL=u6k.apps@gmail.com
    volumes:
      - /etc/localtime:/etc/localtime:ro
    links:
      - zabbix-db:zabbix.db
    restart: always
  zabbix-docker-monitoring:
    image: monitoringartist/zabbix-agent-xxl-limited:latest
    hostname: zabbix-docker-monitoring.local
    environment:
      - ZA_Server=zabbix-server
    volumes:
      - /:/rootfs
    links:
      - zabbix-server:zabbix-server
    restart: always

networks:
  default:
    external:
      name: front_default
