- hosts: localhost
  connection: local
  gather_facts: no
  sudo: no
  vars:
    homebrew_taps:
      - homebrew/binary
      - homebrew/dupes
      - caskroom/cask
    homebrew_packages:
      - { name: rbenv }
      - { name: ruby-build }
      - { name: vim }
      - { name: ansible }
      - { name: pyenv }
      - { name: git }
      - { name: wget }
    homebrew_cask_packages:
      - { name: java }
      - { name: dropbox }
      - { name: virtualbox }
      - { name: vagrant }
      - { name: kobito }
      - { name: atom }
      - { name: google-chrome }
      - { name: adobe-reader }
      - { name: skype }
      - { name: slack }
      - { name: sourcetree }
      - { name: skitch }
      - { name: atom }
      - { name: iterm2 }
  tasks:
    - name: install taps of homebrew
      homebrew_tap: tap="{{ item }}" state=present
      with_items: homebrew_taps
    - name: update homebrew
      homebrew: update_homebrew=yes
    - name: install homebrew packages
      homebrew: name="{{ item.name }}" state="{{ item.state|default('latest') }}" install_options="{{ item.install_options|default() }}"
      with_items: homebrew_packages
    - name: update brew-cask
      homebrew: name=brew-cask state=latest
    - name: install homebrew cask packages
      homebrew_cask: name="{{ item.name }}" state=present
      with_items: homebrew_cask_packages

