version: '2'

services:
  jenkins:
    image: axltxl/jenkins-dood
    volumes:
      - /mnt/data/docker/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/bin/docker.io
      - /usr/lib/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02
    environment:
      - JAVA_OPTS="-Duser.timezone=Asia/Tokyo"
      - VIRTUAL_HOST=jenkins.u6k.me
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=jenkins.u6k.me
      - LETSENCRYPT_EMAIL=u6k.apps@gmail.com
    restart: always

networks:
  default:
    external:
      name: front_default
