version: '2'

services:
  jenkins:
    build: .
    volumes:
      - /mnt/data/docker/jenkins:/root/.jenkins
      - /mnt/backup:/mnt/backup
      - /mnt/data:/mnt/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /usr/bin/docker:/usr/bin/docker:ro
    environment:
      - VIRTUAL_HOST=jenkins.u6k.me
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=jenkins.u6k.me
      - LETSENCRYPT_EMAIL=u6k.apps@gmail.com
    restart: always

networks:
  default:
    external:
      name: front_default
