version: '2'

services:
  jenkins:
    build: .
    volumes:
      - /mnt/data/docker/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - VIRTUAL_HOST=jenkins.u6k.me
      - VIRTUAL_PORT=8080
    restart: always

networks:
  default:
    external:
      name: front_default
