version: '2'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab.u6k.me
    volumes:
      - /mnt/data/docker/gitlab/config:/etc/gitlab
      - /mnt/data/docker/gitlab/logs:/var/log/gitlab
      - /mnt/data/docker/gitlab/data:/var/opt/gitlab
    environment:
      - VIRTUAL_HOST=gitlab.u6k.me
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=gitlab.u6k.me
      - LETSENCRYPT_EMAIL=u6k.apps@gmail.com
      - GITLAB_OMNIBUS_CONFIG="external_url 'https://gitlab.u6k.me';"
#    ports:
#      - "22:22"
    restart: always
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    volumes:
      - /mnt/data/docker/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

networks:
  default:
    external:
      name: front_default
