version: '2'

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    hostname: gitlab.u6k.me
    volumes:
      - /mnt/data/docker/gitlab/config:/etc/gitlab
      - /mnt/data/docker/gitlab/logs:/var/log/gitlab
      - /mnt/data/docker/gitlab/data:/var/opt/gitlab
      - /mnt/data/docker/letsencrypt/certs/archive/gitlab.u6k.me/fullchain1.pem:/etc/gitlab/ssl/gitlab.u6k.me.crt
      - /mnt/data/docker/letsencrypt/certs/archive/gitlab.u6k.me/privkey1.pem:/etc/gitlab/ssl/gitlab.u6k.me.key
    environment:
      - VIRTUAL_HOST=gitlab.u6k.me
      - VIRTUAL_PORT=443
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=gitlab.u6k.me
      - LETSENCRYPT_EMAIL=u6k.apps@gmail.com
#    ports:
#      - "22:22"
    restart: always
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    volumes:
      - /mnt/data/docker/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  registry:
    image: registry:2
    environment:
      - REGISTRY_HTTP_TLS_CERTIFICATE=/certs/registry.u6k.me.crt
      - REGISTRY_HTTP_TLS_KEY=/certs/registry.u6k.me.key
      - VIRTUAL_HOST=registry.u6k.me
      - VIRTUAL_PORT=5000
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=registry.u6k.me
      - LETSENCRYPT_EMAIL=u6k.apps@gmail.com
    volumes:
      - /mnt/data/docker/registry/data:/var/lib/registry
      - /mnt/data/docker/letsencrypt/certs/archive/registry.u6k.me/fullchain1.pem:/certs/registry.u6k.me.crt:ro
      - /mnt/data/docker/letsencrypt/certs/archive/registry.u6k.me/privkey1.pem:/certs/registry.u6k.me.key:ro
    restart: always
  registry-frontend:
    image: konradkleine/docker-registry-frontend:v2
    environment:
      - ENV_DOCKER_REGISTRY_HOST=registry.u6k.me
      - ENV_DOCKER_REGISTRY_PORT=443
      - ENV_DOCKER_REGISTRY_USE_SSL=1
      - VIRTUAL_HOST=registry-web.u6k.me
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=registry-web.u6k.me
      - LETSENCRYPT_EMAIL=u6k.apps@gmail.com
    restart: always

networks:
  default:
    external:
      name: front_default
