version: '3'

services:
  rundeck:
    image: u6kapps/rundeck
    env_file:
      - ./.env
    volumes:
      - ${DOCKER_VOLUMES}/rundeck/data:/home/rundeck/server/data
      - ${DOCKER_VOLUMES}/rundeck/logs:/home/rundeck/var/logs
      - ${DOCKER_VOLUMES}/rundeck/projects:/home/rundeck/projects
      - ./realm.properties:/home/rundeck/server/config/realm.properties
      - ./tokens.properties:/home/rundeck/etc/tokens.properties
      - /dev/null:/home/rundeck/etc/rundeckpro-license.key
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${DOCKER_VOLUMES}/redmine:/mnt/docker-volumes/redmine:ro
    restart: always

networks:
  default:
    external:
      name: production
