version: '2'

services:
  nginx-proxy:
    image: u6kapps/nginx-proxy
    privileged: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "cert:/etc/nginx/certs:ro"
      - "htpasswd:/etc/nginx/htpasswd:ro"
      - "/etc/nginx/vhost.d"
      - "/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    restart: always
  cert:
    image: jrcs/letsencrypt-nginx-proxy-companion
    privileged: true
    volumes:
      - "cert:/etc/nginx/certs:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - nginx-proxy
    depends_on:
      - nginx-proxy
    restart: always

volumes:
  cert:
    driver: local
  htpasswd:
    driver: local

#networks:
#  default:
#    external:
#      name: bridge
