version: '3'

services:
  rundeck:
    image: u6kapps/rundeck
    environment:
      - "RDECK_URL=https:\\/\\/rundeck\\.u6k\\.me"
      - "RDECK_ADMIN_USER=${DOCKER_RDECK_ADMIN_USER}"
      - "RDECK_ADMIN_PASS=${DOCKER_RDECK_ADMIN_PASS}"
      - "AWS_ACCESS_KEY_ID=${DOCKER_MINIO_ACCESS_KEY}"
      - "AWS_SECRET_ACCESS_KEY=${DOCKER_MINIO_SECRET_KEY}"
      - "AWS_DEFAULT_REGION=us-east-1"
      - "AWS_S3_ENDPOINT=http://minio:9000"
      - "VIRTUAL_HOST=rundeck.u6k.me"
      - "VIRTUAL_PORT=4440"
      - "LETSENCRYPT_HOST=rundeck.u6k.me"
      - "LETSENCRYPT_EMAIL=u6k.apps@gmail.com"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "rundeck_projects:/opt/rundeck/projects/"
      - "rundeck_data:/opt/rundeck/server/data/"
      - "rundeck_logs:/opt/rundeck/var/logs/"
    restart: always

volumes:
  rundeck_projects:
    driver: local
  rundeck_data:
    driver: local
  rundeck_logs:
    driver: local

networks:
  default:
    external:
      name: docker_default
