version: "3"

services:
  mlflow:
    image: ghcr.io/u6k/mlflow
    env_file:
      - ./.env
    environment:
      - VIRTUAL_HOST=${DOCKER_VIRTUAL_HOST}
      - VIRTUAL_PORT=${DOCKER_VIRTUAL_PORT}
      - LETSENCRYPT_HOST=${DOCKER_LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${DOCKER_LETSENCRYPT_EMAIL}
    command: mlflow server --backend-store-uri 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}' --default-artifact-root '${S3_PATH}' --host 0.0.0.0 --port 5000
    depends_on:
      - db
    restart: always
  db:
    image: postgres:13
    env_file:
      - ./.env
    volumes:
      - ${DOCKER_VOLUMES}/mlflow/db:/var/lib/postgresql/data
    restart: always

networks:
  default:
    external:
      name: production
