version: '3'

services:
  notebook:
    image: jupyter/datascience-notebook
    user: "root"
    ports:
      - "8888:8888"
    environment:
      - "TZ=Asia/Tokyo"
      - "JUPYTER_ENABLE_LAB=yes"
      - "GRANT_SUDO=yes"
    volumes:
      - "${DOCKER_VOLUMES}/jupyter:/home/jovyan/work"
    command: start-notebook.sh
    restart: always

networks:
  default:
    external:
      name: production
