version: '3'

services:
  notebook:
    image: ghcr.io/u6k/jupyter:latest
    user: root
    ports:
      - 8888:8888
    volumes:
      - ${DOCKER_VOLUMES}/jupyter/work:/home/jovyan/work
      - ${DOCKER_VOLUMES}/jupyter/settings:/home/jovyan/.jupyter
    command: start-notebook.sh --ServerApp.password='${JUPYTER_PASSWORD}'
    extra_hosts:
      - s3.192.168.local:192.168.3.202
    restart: always
    shm_size: 1gb

networks:
  default:
    external:
      name: production
