# apt update and upgrade
- name: apt update and upgrade
  apt: update_cache=yes upgrade=full

# ssh setting
- name: ssh setting - RSAAuthentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="RSAAuthentication" line="RSAAuthentication yes" state=present
- name: ssh setting - PubkeyAuthentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="PubkeyAuthentication" line="PubkeyAuthentication yes" state=present
  notify: restart sshd
- name: ssh setting - PermitRootLogin
  lineinfile: dest=/etc/ssh/sshd_config regexp="PermitRootLogin" line="PermitRootLogin no" state=present
  notify: restart sshd
- name: ssh setting - RhostsRSAAuthentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="RhostsRSAAuthentication" line="RhostsRSAAuthentication no" state=present
  notify: restart sshd
- name: ssh setting - PasswordAuthentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="PasswordAuthentication" line="PasswordAuthentication no" state=present
  notify: restart sshd
- name: ssh setting - PermitEmptyPasswords
  lineinfile: dest=/etc/ssh/sshd_config regexp="PermitEmptyPasswords" line="PermitEmptyPasswords no" state=present
  notify: restart sshd
- name: ssh setting - ChallengeResponseAuthentication
  lineinfile: dest=/etc/ssh/sshd_config regexp="ChallengeResponseAuthentication" line="ChallengeResponseAuthentication no" state=present
  notify: restart sshd
