#cloud-config

hostname: coreos

coreos:
  units:
    - name: etcd.service
      command: start
    - name: docker.service
      command: start
    - name: fleet.service
      command: start
    - name: timezone.service
      command: start
      content: |
        [Unit]
        Description=timezone
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/bin/ln -sf ../usr/share/zoneinfo/Japan /etc/localtime

users:
  - name: u6k
    passwd: $1$6dXJA246$2HCEnF3W2LcDYvNSREA4n0
    groups:
      - sudo
      - docker
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAEAQD9BCawE47HvgZiPpVeEka50pSVzm9tOUtNVUaJy01OdiJKpHAX+4jt96TVDNSpe0o/2R9tNftFHpn3161OmpEjHukzRo6h6GtqMsa7GmG3vlD3227IXGOwNnsxm7OFvPmjXxPnttUfNoJtMPr4mKiw4nGZCvLPEot/Y9Aogul1vutvdg1Gc42r2l2G9LmrEuUh5fS28CQOlpHL+SwMV39znXHvDugPf0t5lzS1t20fhbVdvciGIUtlWhrFEsM8Bs/rvrrBW8d88efqhGRIMe3cAPS9FiC4l7YF+Yx3U+fBQBFqlIgg9s2VxQ6kMw963AZ7Ep1goafiFdwmVcLQbnGL6IwLj1fu83v58LALDA5O+sB59ZIRJDVG4SKrhCGqoq0rySh8ZW2471joUai60OB+QMYBpqu7u18VgUiQWTDXgRSL4Sd2Ec6L0EZhQx6dzrmruKXuhIK/g9YL5tg2Obs/UHflBO1eOBw5fVgJnMaXcEwHDkLAWVHPsFAwBX9rOlCEdNKKqdRZS9KImObkVEJV1cxcCye7ki3wRqDyZm7hhIOvcCzKE3H3MIRxt5VI3g0Q4xA5CSAFeANdscBHz86tgV5Kcz7qo6ByAxaPz+pvAmw/ldnpoooS8DYBODKhe8TR91GeG1xXl/SBKmm4UisYNn1m6BUX/kPGOhd5ev1QXmmbXcePvh+G5x1qrErBlQ++dUzE68WuGLCquf9bxgIk17V1IYkZm+AkK/A4dddJBFWUN9DYtEFhvjZL6aEBoWcIYvIYCz+x/NGVrbndBJlcShUuWwDHcC2nCO8OAZpUatd6NfPiQHQENHwNFz1jJk/NCE82HtCso7yVwgO4jgs7OrVTRZs2jn38G35zfQtcGJVyHfxpLNWWQV9ywlbTsuh7x4+yQrZYYUx0Ak6nrjNgCJ5R8mGt6w0Dc+0B7ZEOHBQEDu58CDERnwApB2QHwJyJ63S0Ixi/oiY/YsAOh7TODaTRhN04cQkQLHRgWQukTL13Nr5PcG8QKX7QeSbLImgwayuGyn+liBVdlkLNahOvmQPHpTj2gnrZrdlm8976O77wZlB9uYSw8SLbRuAgGBeXEOrLicq0ZLmLYKpoXBKbOx9J7eG7AK9ROYMc4vCVTVGF2+9jh/ErbOposGwPeX344ZNfLVTnCBA+NwCL57G2t/Jjdr5EGXzmapmAZCi9fLjmiHtoEYcf+xL5dbxtT9fVhlurtDk0dsrucmO44g9YUu/9qVZiKNxhVaF272wQQjCeKsbCZ/sIG2920zCZNUKFRM5vCWL7lmqNJTZsRkyKYZDRCu7ZIcozWKY9fkl8B7Ps1VPd/cRG+xD5GdhGNhgWMIS44Z1XiTX6M+T9re3F
