version: '2'

services:
  redmine-mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_DATABASE=redmine_db
      - MYSQL_USER=redmine_user
      - MYSQL_PASSWORD=redmine_pass
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - /mnt/data/docker/redmine/mysql:/var/lib/mysql
    restart: always
  redmine:
    image: redmine
    environment:
      - VIRTUAL_HOST=redmine.u6k.me
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=redmine.u6k.me
      - LETSENCRYPT_EMAIL=u6k.apps@gmail.com
    volumes:
      - /mnt/data/docker/redmine/data:/usr/src/redmine/files
    links:
      - redmine-mysql:mysql
    restart: always

networks:
  default:
    external:
      name: front_default
