version: '3'

services:
  app:
    image: u6kapps/investment-local-horse-racing-crawler
    environment:
      - "TZ=Asia/Tokyo"
      - "VIRTUAL_HOST=local-horse-racing-crawler.u6k.me"
      - "VIRTUAL_PORT=5000"
      - "LETSENCRYPT_HOST=local-horse-racing-crawler.u6k.me"
      - "LETSENCRYPT_EMAIL=u6k.apps@gmail.com"
      - "S3_ENDPOINT=${DOCKER_S3_ENDPOINT}"
      - "S3_REGION=${DOCKER_S3_REGION}"
      - "S3_ACCESS_KEY=${DOCKER_S3_ACCESS_KEY}"
      - "S3_SECRET_KEY=${DOCKER_S3_SECRET_KEY}"
      - "S3_BUCKET=${DOCKER_LOCAL_HORSE_RACING_CRAWLER_S3_BUCKET}"
      - "S3_FOLDER=${DOCKER_LOCAL_HORSE_RACING_CRAWLER_S3_FOLDER}"
      - "DB_HOST=${DOCKER_LOCAL_HORSE_RACING_CRAWLER_DB_HOST}"
      - "DB_PORT=${DOCKER_LOCAL_HORSE_RACING_CRAWLER_DB_PORT}"
      - "DB_USERNAME=${DOCKER_LOCAL_HORSE_RACING_CRAWLER_DB_USERNAME}"
      - "DB_PASSWORD=${DOCKER_LOCAL_HORSE_RACING_CRAWLER_DB_PASSWORD}"
      - "DB_DATABASE=${DOCKER_LOCAL_HORSE_RACING_CRAWLER_DB_DATABASE}"
    restart: always

networks:
  default:
    external:
      name: production
