version: '3'

services:
  app:
    image: u6kapps/investment-local-horse-racing-crawler
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - ${DOCKER_VOLUMES}/local-horse-racing-crawler/db:/var/lib/postgresql/data
      - ${DOCKER_VOLUMES}/local-horse-racing-crawler/wal_archive:/archive
    restart: always

networks:
  default:
    external:
      name: production
