version: '3'

services:
  app:
    image: u6kapps/investment-local-horse-racing-crawler
    environment:
      - "TZ=Asia/Tokyo"
      - "S3_ENDPOINT=${S3_ENDPOINT}"
      - "S3_REGION=${S3_REGION}"
      - "S3_ACCESS_KEY=${S3_ACCESS_KEY}"
      - "S3_SECRET_KEY=${S3_SECRET_KEY}"
      - "S3_BUCKET=${S3_BUCKET}"
      - "S3_FOLDER=${S3_FOLDER}"
      - "DB_HOST=${DB_HOST}"
      - "DB_PORT=${DB_PORT}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "DB_DATABASE=${DB_DATABASE}"
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - "${DOCKER_VOLUMES}/local-horse-racing-crawler/db:/var/lib/postgresql/data"
      - "${DOCKER_VOLUMES}/local-horse-racing-crawler/wal_archive:/archive"
    environment:
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_DB=${DB_DATABASE}"
    restart: always

networks:
  default:
    external:
      name: production
