owncloud:
  image: owncloud
  environment:
    - VIRTUAL_HOST=owncloud.u6k.me
    - VIRTUAL_PORT=80
    - LETSENCRYPT_HOST=owncloud.u6k.me
    - LETSENCRYPT_EMAIL=u6k.apps@gmail.com
  restart: always
